spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/guard?useUnicode=true&amp
    username: root
    password: P@ssw0rd
    hikari:
      maximum-pool-size: 20
      minimum-idle: 1
      idle-timeout: 600000
      connection-timeout: 60000
      max-lifetime: 1800000